### ISSUE TITLE
Can you tell us more?

### ISSUE THREAD

**Issue by faddat** [nixelsolutions/rancher-vpn-server#1]
Interested in the concept you're exploring here...

**Comment by djskinner** [comment]
+1.

I've followed the guide that pretty much explains the concept here: http://rancher.com/building-a-continuous-integration-environment-using-docker-jenkins-and-openvpn/

It's pretty cool. Would be interested in how to combine this with the internal Rancher DNS for container host name resolution.

**Comment by faddat** [comment]
@djskinner 

I haven't used this, but I'm willing to take a guess as to how to use this to accomplish what you describe.  I'm pretty sure that the rancher server must be exposing a DNS server at port 53.  Therefore, you should be able to add the IP address of the rancher server in your DNS entries on machines that you want to be able to hit containers directly.  Give it a shot!  I'm curious to hear if it works out for you :).

**Comment by djskinner** [comment]
@faddat 

I finally got round to giving this a try but not with much success. I VPN in and can easily access containers by IP address. As you suggest, by adding the IP of one of the Network Agents running on the hosts to my computer's DNS entries I was hoping to access by name. I looked for DNS entries in `/var/lib/cattle/etc/cattle/dns/answers.json` but I get `ERR_NAME_NOT_RESOLVED`.

However, I think this is because the DNS server resolves based on the IP of the requestor and there aren't many resolver entries for "default", which I assume is the catch all. The one name that is in that section does actually resolve:

From `answers.json`:

```
"default": {                                                                    
        "recurse": [                                                            
            "8.8.8.8"                                                           
        ],                                                                      
        "a": {                                                                  
                "rancher-metadata.": {"answer": ["169.254.169.250"]},           
                "rancher-metadata.rancher.internal.": {"answer": ["169.254.169.2
50"]}   
```

```
$ nslookup
> rancher-metadata.rancher.internal
Server:     10.42.247.25
Address:    10.42.247.25#53

Name:   rancher-metadata.rancher.internal
Address: 169.254.169.250
```

So it is working just not exactly as I needed it to.

There is a small chance this issue might help but not sure https://github.com/rancher/rancher/issues/2817

**Comment by djskinner** [comment]
For anyone arriving here there have been some more recent related developments. See:

https://hub.docker.com/r/mdns/rancher-openvpn/

and 

https://github.com/rancher/community-catalog/pull/21

**Comment by faddat** [comment]
@djskinner 
Awesome!  Thanks for the update and links, I'm going to have a look around :).

**Comment by ElPsyCongro** [comment]
Hi I have a rancher-server on a local server and what I'm trying to do is add my AWS host with his public IP but they can reach my local server only by VPN connection. (When I execute the command generated by the UI of Rancher to add a host the detected cattle agent IP is his IP of the VPN even when use the public IP of the host for cattle agent IP).
Every host has a OpenVPN client that is running on background providing a tun0 interface, I have a VPN server on AWS that allows connection between clients and redirect all the traffic through the VPN. Also my local server is connected to that VPN.
The AWS hosts get added but when the second host is added the health check stays on initializing and there is no connection between hosts. Any idea of what is happening? What I'm doing is wrong?
